baseURL = "https://yiannis54.github.io"
languageCode = "en-us"
title = "Wed Development & E-Commerce"
small_title = "Mundo GR."
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id="" #UA-132398315-1

  [params.logo]
    mobile = "images/mundo-logo-mobile.png"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/mundo-2016.png"
    desktop_height = "50px"
    desktop_width = "219px"
    alt = "Mundo Web"

  [params.homepage_meta_tags]
    meta_description = "Mundo e-commerce experts and custom web applications"
    meta_og_title = "Wed Development & E-commerce applications. Mundo GR."
    meta_og_type = "website"
    meta_og_url = "https://www.mundo.gr"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Mundo e-commerce experts and custom web applications"
    meta_twitter_card = "summary"
    meta_twitter_site = "@mundogr"
    meta_twitter_creator = "@mundogr"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 3

[[menu.main]]
    name = "Think Tank"
    url = "#"
    weight = 4

[[menu.main]]
    name = "Request Quote"
    url = "/contact/"
    weight = 5

[permalinks]
  post = "/think-tank/:slug/"
  pages = "/:filename/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true